<%!
            
  String stylePageBODY = "bgcolor=\"#99CCFF\" text=\"#000000\" link=\"#0000FF\" vlink=\"#800080\" alink=\"#FF0000\"";
            
  String styleFormTABLE = " cellpadding=\"0\" border=\"0\" cellspacing=\"0\"";
            
  String styleFormHeaderTD = "align=\"center\" bgcolor=\"#0033cc\"";
            
  String styleFormHeaderFONT = "style=\"font-size: 12pt; color: #FFFFFF; font-family: Arial, Tahoma, Verdana, Helvetica; font-weight: bold\"";
            
  String styleFieldCaptionTD = "bgcolor=\"#DEEFFF\"";
            
  String styleFieldCaptionFONT = "style=\"font-size: 10pt; color: #000000; font-family: Arial, Tahoma, Verdana, Helvetica; font-weight: bold\"";
            
  String styleDataTD = "bgcolor=\"#99CCFF\"";
            
  String styleDataFONT = "style=\"font-size: 15pt; color: #000000; font-family: Arial, Tahoma, Verdana, Helvetica\"";
            
  String styleColumnFONT = "style=\"font-size: 15pt; color: #000000; font-family: Arial, Tahoma, Verdana, Helvetica; font-weight: bold\"";
            
  String styleColumnTD = "bgcolor=\"#DEEFFF\"";
            
%>